DELETE FROM MessageCitations;
DELETE FROM ChatMessages;
DELETE FROM ChatSessions;
DELETE FROM DocumentEmbeddings;
DELETE FROM DocumentChunks;
DELETE FROM DocumentQuizzes;
DELETE FROM Documents;
DELETE FROM AuditLogs;
DELETE FROM SubjectEnrollments;
DELETE FROM UserLoginHistories;
UPDATE Subjects SET TeacherUserId = NULL;
DELETE FROM Chapters;
DELETE FROM Subjects;
DELETE FROM AppUsers WHERE Email <> N'admin@gmail.com';
